FORMAT: 1A
# Target MVD

# Group Auth

## Registrations [/auth]

+ Attributes (object)
  + email (required) - Email
  + password (required) - Password
  + current_password (required) - Current password

### Create [POST]

+ Request Ok

    + Body

            {"email":"user-1@example.com","password":"P@55word"}

+ Response 200 ()

    + Body

            {
              "status": "success",
              "data": {
                "id": 1,
                "email": "user-1@example.com",
                "created_at": "2019-05-17T13:48:53.975Z",
                "updated_at": "2019-05-17T13:48:53.975Z",
                "provider": "email",
                "uid": "user-1@example.com",
                "allow_password_change": false,
                "type": "user"
              }
            }

### Update [PUT]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-2@example.com

    + Body

            {"current_password":"P@55word","email":"new-email-1@example.com","password":"n3w-p@55word"}

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: new-email-1@example.com

    + Body

            {
              "status": "success",
              "data": {
                "id": 2,
                "email": "new-email-1@example.com",
                "provider": "email",
                "uid": "new-email-1@example.com",
                "created_at": "2019-05-17T13:48:54.204Z",
                "updated_at": "2019-05-17T13:48:54.311Z",
                "allow_password_change": false,
                "type": "user"
              }
            }

## Session [/auth/sign_in]

+ Attributes (object)
  + email (required) - Email
  + password (required) - Password

### Create [POST]

+ Request Ok

    + Body

            {"email":"user-3@example.com","password":"P@55word"}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1559310534
            uid: user-3@example.com

    + Body

            {
              "data": {
                "id": 3,
                "email": "user-3@example.com",
                "provider": "email",
                "uid": "user-3@example.com",
                "allow_password_change": false,
                "type": "user"
              }
            }

## Session [/auth/sign_out]

### Delete [DELETE]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-4@example.com

+ Response 200 ()

    + Body

            {
              "success": true
            }

## Password [/auth/password]

+ Attributes (object)
  + email (required) - Email
  + redirect_url (required) - Url to which the user will be redirected after visiting
                                  the link contained in the email

### Reset password email [POST]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-5@example.com

    + Body

            {"email":"user-5@example.com","redirect_url":"http://anywhere.com"}

+ Response 200 ()

    + Body

            {
              "success": true,
              "message": "An email has been sent to 'user-5@example.com' containing instructions for resetting your password."
            }

## Facebook [/auth/facebook/callback]

+ Attributes (object)
  + access_token (required) - Access token provided by facebook

### Login or Sign up [POST]

+ Request Ok

    + Body

            {"facebook":{"access_token":"acc35T0k3n"}}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1559310534
            uid: existing-user@example.com

    + Body

            {
              "data": {
                "id": "6",
                "type": "users",
                "attributes": {
                  "email": "existing-user@example.com"
                }
              }
            }

# Group Compatible targets

## Compatible targets collection [/compatible_targets]

### Index [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-6@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-6@example.com

    + Body

            {
              "data": [
                {
                  "id": "2",
                  "type": "targets",
                  "attributes": {
                    "area-length": 2000,
                    "lat": 75.6040228365089,
                    "lng": -33.5045664366026,
                    "title": "Dr. Trudi Wilkinson",
                    "topic-id": 1
                  }
                }
              ]
            }

# Group Conversations

## Conversations collection [/conversations]

+ Attributes (object)
  + target_id (required) - Target associated to the conversation

### Create [POST]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-8@example.com

    + Body

            {"conversation":{"target_id":11}}

+ Response 201 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-8@example.com

    + Body

            {
              "data": {
                "id": "4",
                "type": "conversations",
                "attributes": {
                  "unread": true,
                  "status": "active"
                },
                "relationships": {
                  "messages": {
                    "data": [
            
                    ]
                  },
                  "target": {
                    "data": {
                      "id": "11",
                      "type": "targets"
                    }
                  },
                  "initiator": {
                    "data": {
                      "id": "9",
                      "type": "users"
                    }
                  }
                }
              }
            }

### Index [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-13@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-13@example.com

    + Body

            {
              "data": [
                {
                  "id": "5",
                  "type": "conversations",
                  "attributes": {
                    "unread": false,
                    "status": "active"
                  },
                  "relationships": {
                    "messages": {
                      "data": [
            
                      ]
                    },
                    "target": {
                      "data": {
                        "id": "13",
                        "type": "targets"
                      }
                    },
                    "initiator": {
                      "data": {
                        "id": "14",
                        "type": "users"
                      }
                    }
                  }
                },
                {
                  "id": "6",
                  "type": "conversations",
                  "attributes": {
                    "unread": false,
                    "status": "active"
                  },
                  "relationships": {
                    "messages": {
                      "data": [
            
                      ]
                    },
                    "target": {
                      "data": {
                        "id": "14",
                        "type": "targets"
                      }
                    },
                    "initiator": {
                      "data": {
                        "id": "14",
                        "type": "users"
                      }
                    }
                  }
                },
                {
                  "id": "7",
                  "type": "conversations",
                  "attributes": {
                    "unread": false,
                    "status": "active"
                  },
                  "relationships": {
                    "messages": {
                      "data": [
            
                      ]
                    },
                    "target": {
                      "data": {
                        "id": "15",
                        "type": "targets"
                      }
                    },
                    "initiator": {
                      "data": {
                        "id": "14",
                        "type": "users"
                      }
                    }
                  }
                },
                {
                  "id": "8",
                  "type": "conversations",
                  "attributes": {
                    "unread": false,
                    "status": "active"
                  },
                  "relationships": {
                    "messages": {
                      "data": [
            
                      ]
                    },
                    "target": {
                      "data": {
                        "id": "16",
                        "type": "targets"
                      }
                    },
                    "initiator": {
                      "data": {
                        "id": "14",
                        "type": "users"
                      }
                    }
                  }
                }
              ]
            }

## Conversation member [/conversations/{id}]

+ Attributes (object)
  + unread (required) - Flag to mark the conversation as unread

### Show [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-18@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-18@example.com

    + Body

            {
              "data": {
                "id": "9",
                "type": "conversations",
                "attributes": {
                  "unread": false,
                  "status": "active"
                },
                "relationships": {
                  "messages": {
                    "data": [
                      {
                        "id": "1",
                        "type": "messages"
                      },
                      {
                        "id": "2",
                        "type": "messages"
                      },
                      {
                        "id": "3",
                        "type": "messages"
                      },
                      {
                        "id": "4",
                        "type": "messages"
                      },
                      {
                        "id": "5",
                        "type": "messages"
                      }
                    ]
                  },
                  "target": {
                    "data": {
                      "id": "18",
                      "type": "targets"
                    }
                  },
                  "initiator": {
                    "data": {
                      "id": "19",
                      "type": "users"
                    }
                  }
                }
              }
            }

### Update [PUT]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-23@example.com

    + Body

            {"conversation":{"unread":false}}

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-23@example.com

    + Body

            {
              "data": {
                "id": "13",
                "type": "conversations",
                "attributes": {
                  "unread": false,
                  "status": "active"
                },
                "relationships": {
                  "messages": {
                    "data": [
                      {
                        "id": "6",
                        "type": "messages"
                      },
                      {
                        "id": "7",
                        "type": "messages"
                      },
                      {
                        "id": "8",
                        "type": "messages"
                      },
                      {
                        "id": "9",
                        "type": "messages"
                      },
                      {
                        "id": "10",
                        "type": "messages"
                      }
                    ]
                  },
                  "target": {
                    "data": {
                      "id": "23",
                      "type": "targets"
                    }
                  },
                  "initiator": {
                    "data": {
                      "id": "24",
                      "type": "users"
                    }
                  }
                }
              }
            }

# Group Messages

## Messages collection [/conversations/{conversation_id}/messages]

+ Attributes (object)
  + text (required) - Message to send

### Create [POST]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-28@example.com

    + Body

            {"message":{"text":"Everyone has an individual background. Someone may come from Python, someone else may come from Perl, and they may be surprised by different aspects of the language. Then they come up to me and say, 'I was surprised by this feature of the language, so therefore Ruby violates the principle of least surprise.' Wait. Wait. The principle of least surprise is not for you only."}}

+ Response 201 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-28@example.com

    + Body

            {
              "data": {
                "id": "11",
                "type": "messages",
                "attributes": {
                  "text": "Everyone has an individual background. Someone may come from Python, someone else may come from Perl, and they may be surprised by different aspects of the language. Then they come up to me and say, 'I was surprised by this feature of the language, so therefore Ruby violates the principle of least surprise.' Wait. Wait. The principle of least surprise is not for you only.",
                  "created-at": "2019-05-17T13:48:55.880Z",
                  "user-id": 29
                }
              }
            }

# Group Targets

## Targets collection [/targets]

+ Attributes (object)
  + area_length (required) - Area length (meters)
  + lat (required) - Latitude
  + lng (required) - Longitude
  + title (required) - Title
  + topic_id (required) - Topic ID

### Index [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-30@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-30@example.com

    + Body

            {
              "data": [
                {
                  "id": "29",
                  "type": "targets",
                  "attributes": {
                    "area-length": 23,
                    "lat": 36.5171970371127,
                    "lng": -150.207447590894,
                    "title": "Harley Jast",
                    "topic-id": 11
                  }
                },
                {
                  "id": "30",
                  "type": "targets",
                  "attributes": {
                    "area-length": 588,
                    "lat": 33.0035191054114,
                    "lng": 88.0339865220673,
                    "title": "Ivy Marquardt",
                    "topic-id": 12
                  }
                }
              ]
            }

### Create [POST]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-31@example.com

    + Body

            {"target":{"area_length":49,"lat":22.85304113853404,"lng":97.21300162301088,"title":"Trudie Wyman","topic_id":15}}

+ Response 201 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-31@example.com

    + Body

            {
              "data": {
                "id": "34",
                "type": "targets",
                "attributes": {
                  "area-length": 49,
                  "lat": 22.85304113853404,
                  "lng": 97.21300162301088,
                  "title": "Trudie Wyman",
                  "topic-id": 15
                }
              }
            }

## Target member [/targets/{id}]

+ Attributes (object)
  + area_length (required) - Area length (meters)
  + lat (required) - Latitude
  + lng (required) - Longitude
  + title (required) - Title
  + topic_id (required) - Topic ID

### Destroy [DELETE]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-33@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-33@example.com

    + Body

            {
              "data": {
                "id": "37",
                "type": "targets",
                "attributes": {
                  "area-length": 42,
                  "lat": 58.8716800241985,
                  "lng": -164.742632498265,
                  "title": "Phylicia D'Amore",
                  "topic-id": 18
                }
              }
            }

### Update [PUT]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-34@example.com

    + Body

            {"target":{"area_length":427,"lat":15.321664552564613,"lng":-7.3824746090013775,"title":"Cherrie Runte DDS","topic_id":22}}

+ Response 202 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-34@example.com

    + Body

            {
              "data": {
                "id": "40",
                "type": "targets",
                "attributes": {
                  "area-length": 427,
                  "lat": 15.321664552564613,
                  "lng": -7.3824746090013775,
                  "title": "Cherrie Runte DDS",
                  "topic-id": 22
                }
              }
            }

# Group Topics

## Topics collection [/topics]

### Index [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-36@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-36@example.com

    + Body

            {
              "data": [
                {
                  "id": "23",
                  "type": "topics",
                  "attributes": {
                    "name": "Chere Macejkovic"
                  }
                },
                {
                  "id": "24",
                  "type": "topics",
                  "attributes": {
                    "name": "Chasidy Jones"
                  }
                },
                {
                  "id": "25",
                  "type": "topics",
                  "attributes": {
                    "name": "Joelle Krajcik"
                  }
                }
              ]
            }
