FORMAT: 1A
# Target MVD

# Group Compatible targets

## Compatible targets collection [/compatible_targets]

### Index [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-1@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-1@example.com

    + Body

            {
              "data": [
                {
                  "id": "2",
                  "type": "targets",
                  "attributes": {
                    "area-length": 2000,
                    "lat": -30.8457016834139,
                    "lng": 95.8489802219973,
                    "title": "Micah Cole",
                    "topic-id": 1
                  }
                }
              ]
            }

# Group Conversations

## Conversations collection [/conversations]

+ Attributes (object)
  + target_id (required) - Target associated to the conversation
  + initiator_id (required) - ID of the user whom initiated the conversation

### Create [POST]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-3@example.com

    + Body

            conversation[target_id]=4&conversation[initiator_id]=3

+ Response 201 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-3@example.com

    + Body

            {
              "data": {
                "id": "1",
                "type": "conversations",
                "attributes": {
                  "unread": false
                },
                "relationships": {
                  "messages": {
                    "data": [
            
                    ]
                  },
                  "target": {
                    "data": {
                      "id": "4",
                      "type": "targets"
                    }
                  },
                  "initiator": {
                    "data": {
                      "id": "3",
                      "type": "users"
                    }
                  }
                }
              }
            }

### Index [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-8@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-8@example.com

    + Body

            {
              "data": [
                {
                  "id": "5",
                  "type": "conversations",
                  "attributes": {
                    "unread": false
                  },
                  "relationships": {
                    "messages": {
                      "data": [
            
                      ]
                    },
                    "target": {
                      "data": {
                        "id": "9",
                        "type": "targets"
                      }
                    },
                    "initiator": {
                      "data": {
                        "id": "8",
                        "type": "users"
                      }
                    }
                  }
                },
                {
                  "id": "6",
                  "type": "conversations",
                  "attributes": {
                    "unread": false
                  },
                  "relationships": {
                    "messages": {
                      "data": [
            
                      ]
                    },
                    "target": {
                      "data": {
                        "id": "10",
                        "type": "targets"
                      }
                    },
                    "initiator": {
                      "data": {
                        "id": "8",
                        "type": "users"
                      }
                    }
                  }
                },
                {
                  "id": "7",
                  "type": "conversations",
                  "attributes": {
                    "unread": false
                  },
                  "relationships": {
                    "messages": {
                      "data": [
            
                      ]
                    },
                    "target": {
                      "data": {
                        "id": "11",
                        "type": "targets"
                      }
                    },
                    "initiator": {
                      "data": {
                        "id": "8",
                        "type": "users"
                      }
                    }
                  }
                },
                {
                  "id": "8",
                  "type": "conversations",
                  "attributes": {
                    "unread": false
                  },
                  "relationships": {
                    "messages": {
                      "data": [
            
                      ]
                    },
                    "target": {
                      "data": {
                        "id": "12",
                        "type": "targets"
                      }
                    },
                    "initiator": {
                      "data": {
                        "id": "8",
                        "type": "users"
                      }
                    }
                  }
                }
              ]
            }

## Conversation member [/conversations/{id}]

### Show [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-13@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-13@example.com

    + Body

            {
              "data": {
                "id": "13",
                "type": "conversations",
                "attributes": {
                  "unread": false
                },
                "relationships": {
                  "messages": {
                    "data": [
                      {
                        "id": "1",
                        "type": "messages"
                      },
                      {
                        "id": "2",
                        "type": "messages"
                      },
                      {
                        "id": "3",
                        "type": "messages"
                      },
                      {
                        "id": "4",
                        "type": "messages"
                      },
                      {
                        "id": "5",
                        "type": "messages"
                      }
                    ]
                  },
                  "target": {
                    "data": {
                      "id": "14",
                      "type": "targets"
                    }
                  },
                  "initiator": {
                    "data": {
                      "id": "13",
                      "type": "users"
                    }
                  }
                }
              }
            }

# Group Targets

## Targets collection [/targets]

+ Attributes (object)
  + area_length (required) - Area length (meters)
  + lat (required) - Latitude
  + lng (required) - Longitude
  + title (required) - Title
  + topic_id (required) - Topic ID

### Index [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-18@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-18@example.com

    + Body

            {
              "data": [
                {
                  "id": "18",
                  "type": "targets",
                  "attributes": {
                    "area-length": 420,
                    "lat": 47.7274825420241,
                    "lng": -75.7982753752782,
                    "title": "Gerard Feeney III",
                    "topic-id": 5
                  }
                },
                {
                  "id": "19",
                  "type": "targets",
                  "attributes": {
                    "area-length": 631,
                    "lat": -1.96025033020837,
                    "lng": -130.30094321375,
                    "title": "Ruthe Abbott V",
                    "topic-id": 6
                  }
                }
              ]
            }

### Create [POST]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-19@example.com

    + Body

            target[area_length]=397&target[lat]=-23.62426376319054&target[lng]=109.56368762449182&target[title]=Ms.+Shane+Moen&target[topic_id]=9

+ Response 201 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-19@example.com

    + Body

            {
              "data": {
                "id": "23",
                "type": "targets",
                "attributes": {
                  "area-length": 397,
                  "lat": -23.62426376319054,
                  "lng": 109.56368762449182,
                  "title": "Ms. Shane Moen",
                  "topic-id": 9
                }
              }
            }

## Target member [/targets/{id}]

### Destroy [DELETE]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: user-21@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry:  
            uid: user-21@example.com

    + Body

            {
              "data": {
                "id": "26",
                "type": "targets",
                "attributes": {
                  "area-length": 485,
                  "lat": 80.8023565578692,
                  "lng": -40.4369920443589,
                  "title": "Darryl Bosco Sr.",
                  "topic-id": 12
                }
              }
            }
