FORMAT: 1A
# Target MVD

# Group Compatible targets

## Compatible targets collection [/compatible_targets]

### Index [GET]

+ Request Ok

    + Headers

            Access-Token: 3HI_qgFOIogduVODuFp9RQ
            Client: lTj-rlExEgPwJ0krxGvr3Q
            Uid: user-1@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: lTj-rlExEgPwJ0krxGvr3Q
            expiry:  
            uid: user-1@example.com

    + Body

            [
              {
                "area_length": 2000,
                "id": 753,
                "lat": 54.4185207749279,
                "lng": 115.138932728875,
                "title": "Otto Skiles III",
                "topic_id": 645
              }
            ]

# Group Targets

## Targets collection [/targets]

+ Attributes (object)
  + area_length (required) - Area length (meters)
  + lat (required) - Latitude
  + lng (required) - Longitude
  + title (required) - Title
  + topic_id (required) - Topic ID

### Index [GET]

+ Request Ok

    + Headers

            Access-Token: jd9v1BhcCzB8w6AtOjpVQA
            Client: nvryv82L7XrOEFj8QOmWsA
            Uid: user-3@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: nvryv82L7XrOEFj8QOmWsA
            expiry:  
            uid: user-3@example.com

    + Body

            [
              {
                "area_length": 837,
                "id": 754,
                "lat": -79.7899491107017,
                "lng": 89.7811955156606,
                "title": "Shane Walter",
                "topic_id": 646
              },
              {
                "area_length": 868,
                "id": 755,
                "lat": -88.3846185416942,
                "lng": 152.251552740167,
                "title": "Woodrow Kemmer I",
                "topic_id": 647
              }
            ]

### Create [POST]

+ Request Ok

    + Headers

            Access-Token: tsgtZdqR5Hu29G9btcskog
            Client: GxKu4QtsW7A7sLroiJi7Hg
            Uid: user-4@example.com

    + Body

            target[area_length]=359&target[lat]=-29.275948887576433&target[lng]=-69.2516961938706&target[title]=Darren+Gaylord&target[topic_id]=650

+ Response 201 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: GxKu4QtsW7A7sLroiJi7Hg
            expiry:  
            uid: user-4@example.com

    + Body

            {
              "area_length": 359,
              "id": 759,
              "lat": -29.275948887576433,
              "lng": -69.2516961938706,
              "title": "Darren Gaylord",
              "topic_id": 650
            }

## Target member [/targets/{id}]

### Destroy [DELETE]

+ Request Ok

    + Headers

            Access-Token: QGiUVNLJUdPWsuCX1bPPKw
            Client: KfTWOZQuwstuZMavU7F5dg
            Uid: user-6@example.com

+ Response 200 ()

    + Headers

            access-token:  
            token-type: Bearer
            client: KfTWOZQuwstuZMavU7F5dg
            expiry:  
            uid: user-6@example.com

    + Body

            {
              "area_length": 820,
              "id": 762,
              "lat": 9.74187920337859,
              "lng": -138.036442516321,
              "title": "Eliza Gusikowski",
              "topic_id": 653
            }
