test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use the application.yml file to set the AWS secrets (as AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY_ID)
amazon:
  service: S3
  region: <%= ENV.fetch('AWS_REGION') %>
  bucket: <%= ENV.fetch('AWS_BUCKET') %>
